server:
  servlet:
    context-path: /ams
  error:
    include-stacktrace: always

spring:
  # datasource
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:5432}/ams
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        order_inserts: false
        jdbc:
          batch_size: 1000